### ISSUE TITLE
404 responses are actually 200 OK

### ISSUE THREAD

**Issue by acropup** [vhs/api#10]
Queries that should return a 404 or similar error return a 200 OK with the body text containing the response code. They should actually be providing a 404 response and I-don't-really-care-what for a body.

Example:
http://api.vanhack.ca/s/vhs/data/invalidname
http://api.vanhack.ca/s/vhs/data/invalidname.json
http://api.vanhack.ca/s/vhs/data/invalidname.txt

**Comment by TyIsI** [comment]
Handled in #13
