### ISSUE TITLE
Make VHSAPI Docker Image

### ISSUE THREAD

**Issue by acropup** [vhs/api#3]
http://api.hackspace.ca needs to be migrated to the Talk server, which uses [docker](https://www.docker.com/) to manage its web services. We'll need to create a docker image of VHSAPI, deploy it to the Talk server, test it, and then reconfigure DNS entries for api.hackspace.ca and isvhsopen.com.

**Important setup files:**
[README.md](https://github.com/vhs/api/blob/master/README.md) - install notes
[INSTALL.sh](https://github.com/vhs/api/blob/master/INSTALL.sh) - moves the config scritps below
etc/service/vhsapi/[run](https://github.com/vhs/api/blob/master/etc/service/vhsapi/run) - starts perl service
etc/nginx/[vhs-api](https://github.com/vhs/api/blob/master/etc/nginx/vhs-api) - nginx config

Here is a start to a Dockerfile:
```
FROM ubuntu         #Not sure what the Talk server is running

RUN apt-get update && apt-get install libexpat1-dev libssl-dev daemontools daemontools-run
#Do we need to apt-get carton as well?
RUN carton install

EXPOSE 3000        #VHSAPI listens on this port
CMD ["api/etc/service/vhsapi/run"]
```

**Comment by interlock** [comment]
@acropup Any thoughts on where Redis should be running for this? Ideally another container we link to this one (or pass an ENV indicating where to look).

Taking nginx out, since the machine running talk already runs it and we can route it there. I'll just open up port 3000 like your example shows. 

Installing carton and doing `carton install` takes AGES btw... why perl... WHY?

**Comment by acropup** [comment]
Yes, ideally it'd be in another container, but I don't know if making that separation is worth the effort at this point.

Regarding the exposed port, I found out that the [EXPOSE command](https://docs.docker.com/reference/builder/#expose) is probably not what we want. If nginx is running within a Docker container, then we can continue to use EXPOSE, but otherwise, EXPOSE is unnecessary and we instead need to use the -p flag in the docker run command:
```> docker run -p 3000 [...]```
This is because EXPOSE apparently does not expose the port publicly, but only makes it available to other docker containers. ```-p``` makes the port public.
Either way, I'm pretty sure that nginx is listening on port 80, so we just need to make sure that nginx knows port 3000 by way of the config file ```api/etc/nginx/vhs-api```. If we do use EXPOSE, it should be left as:
```EXPOSE 3000``` rather than 
```EXPOSE 3000 80``` (this tells docker that this container is listening on ports 3000 and 80, which is not true)
