### ISSUE TITLE
datapoint.js validation comments

### ISSUE THREAD

**Issue by acropup** [vhs/api#7]
api/src/datapoint.js

The following two function names, along with their comments, imply that the functions do more validation than they actually do. I don't know where these functions are used, so I'm not sure if it's the names and comments that are wrong, or if the body of the functions needs fixing. @interlock?

49:
  // validate the space and datapoint name
  _validateSpaceName: function(space, name) {

56:
  // validate the space and datapoint name, value pair
  _validateSpaceNameValue: function(space, name, value) {

**Comment by interlock** [comment]
stubs because while the old implementation implied support for namespaces, it was not used/enabled.
